[package]
name = "crossbow"
version = "0.1.0"
edition = "2021"
authors = ["DodoRare Team <support@dodorare.com>"]
description = "Cross-Platform Rust Toolkit for Games 🏹"
repository = "https://github.com/dodorare/crossbow"
license = "Apache-2.0"
keywords = ["build", "android", "apple", "ios", "tools"]
readme = "README.md"
exclude = [".github/**/*"]

[dependencies]
creator-derive = { path = "crates/creator-derive", version = "0.4.1" }

creator-ads = { path = "crates/creator-ads", version = "0.4.1", optional = true }
creator-tools = { path = "crates/creator-tools", version = "0.4.1", optional = true }
creator-permissions = { path = "crates/creator-permissions", version = "0.4.1", optional = true }

[target.'cfg(target_os = "android")'.dependencies]
ndk-glue = "0.4"

[features]
default = []

[workspace]
members = [
    "crates/*",
    "examples/*",
]
