[package]
name = "creator"
version = "0.2.1"
edition = "2018"
authors = ["enfipy <enfipy@gmail.com>", "olvyko <olvyko@gmail.com>"]
description = "Mobile Game Framework"
repository = "https://github.com/creator-rs/creator"
license = "Apache-2.0"
keywords = ["build", "android", "ios", "substrate"]
readme = "README.md"
exclude = [".github/**/*"]

[dependencies]
cargo-creator = { path = "crates/cargo-creator", version = "0.2.1", optional = true }
creator-derive = { path = "crates/creator-derive", version = "0.2.1" }
creator-permissions = { path = "crates/creator-permissions", version = "0.2.1", optional = true }

[target.'cfg(target_os = "android")'.dependencies]
ndk-glue = { version = "0.2", features = ["logger"] }
android_logger = "0.9"

# [patch.crates-io]
# cpal = { git = "https://github.com/creator-rs/cpal", rev = "f85ad0c7d0c528d45893306b639a22ead10acc31" }

[features]
default = []
tool = ["cargo-creator"]
permissions = ["creator-permissions"]

[workspace]
members = [
    "crates/*",
    "examples/*",
    "examples/substrate/runtime",
]
