[package]
name = "creator"
version = "0.1.1"
edition = "2018"
authors = ["enfipy <enfipy@gmail.com>", "olvyko <olvyko@gmail.com>"]
description = "Mobile Game Framework"
repository = "https://github.com/creator-rs/creator"
license = "Apache-2.0"
keywords = ["build", "android", "ios", "substrate"]
readme = "README.md"
exclude = [".github/**/*"]

[dependencies]
creator-permissions = { path = "crates/creator-permissions", version = "0.1.1", optional = true }

[patch.crates-io]
oboe = { git = "https://github.com/enfipy/oboe-rs", branch = "patch-1" }
cpal = { git = "https://github.com/RustAudio/cpal" }

[features]
permissions = ["creator-permissions"]

[workspace]
members = [
    "crates/*",
    "examples/*",
    "examples/substrate/runtime",
]
