[package]
name = "creator"
version = "0.2.1"
edition = "2018"
authors = ["enfipy <enfipy@gmail.com>", "olvyko <olvyko@gmail.com>"]
description = "Mobile Game Framework"
repository = "https://github.com/creator-rs/creator"
license = "Apache-2.0"
keywords = ["build", "android", "apple", "ios", "substrate", "tools"]
readme = "README.md"
exclude = [".github/**/*"]

[dependencies]
creator-derive = { path = "crates/creator-derive", version = "0.2.1" }

creator-ads = { path = "crates/creator-ads", version = "0.2.1", optional = true }
creator-tools = { path = "crates/creator-tools", version = "0.2.1", optional = true }
creator-permissions = { path = "crates/creator-permissions", version = "0.2.1", optional = true }

[target.'cfg(target_os = "android")'.dependencies]
ndk-glue = "0.2"

[patch.crates-io]
# bevy = { path = "../bevy" }
# bevy = { git = "https://github.com/bevyengine/bevy", rev = "61b181a699ed2b450bebc8c14d96c6af55fa41cf" }
cpal = { git = "https://github.com/MichaelHills/cpal", branch = "mike-ios" }
plist = { git = "https://github.com/creator-rs/rust-plist", branch = "master" }

[features]
default = []

[workspace]
members = [
    "crates/*",
    "examples/*",
    "examples/substrate/runtime",
]
