[package]
name = "creator"
version = "0.2.1"
edition = "2018"
authors = ["enfipy <enfipy@gmail.com>", "olvyko <olvyko@gmail.com>"]
description = "Mobile Game Framework"
repository = "https://github.com/creator-rs/creator"
license = "Apache-2.0"
keywords = ["build", "android", "ios", "substrate"]
readme = "README.md"
exclude = [".github/**/*"]

[dependencies]
cargo-creator = { path = "crates/cargo-creator", version = "0.2.1", optional = true }
creator-derive = { path = "crates/creator-derive", version = "0.2.1" }
creator-permissions = { path = "crates/creator-permissions", version = "0.2.1", optional = true }

[target.'cfg(target_os = "android")'.dependencies]
ndk-glue = { version = "0.2", features = ["logger"] }
android_logger = "0.9"

[patch.crates-io]
# bevy = { path = "../bevy" }
bevy = { git = "https://github.com/bevyengine/bevy", rev = "509b138e8fa3ea250393de40c33cc857c72134d3" }
cpal = { git = "https://github.com/MichaelHills/cpal", branch = "mike-ios" }

# sp-arithmetic = { git = "https://github.com/paritytech/substrate", rev = "c60f00840034017d4b7e6d20bd4fcf9a3f5b529a" }
# frame-support = { git = "https://github.com/paritytech/substrate", rev = "c60f00840034017d4b7e6d20bd4fcf9a3f5b529a" }
# frame-system = { git = "https://github.com/paritytech/substrate", rev = "c60f00840034017d4b7e6d20bd4fcf9a3f5b529a" }
# sp-runtime = { git = "https://github.com/paritytech/substrate", rev = "c60f00840034017d4b7e6d20bd4fcf9a3f5b529a" }
# sp-version = { git = "https://github.com/paritytech/substrate", rev = "c60f00840034017d4b7e6d20bd4fcf9a3f5b529a" }
# pallet-indices = { git = "https://github.com/paritytech/substrate", rev = "c60f00840034017d4b7e6d20bd4fcf9a3f5b529a" }
# pallet-staking = { git = "https://github.com/paritytech/substrate", rev = "c60f00840034017d4b7e6d20bd4fcf9a3f5b529a" }
# pallet-timestamp = { git = "https://github.com/paritytech/substrate", rev = "c60f00840034017d4b7e6d20bd4fcf9a3f5b529a" }
# pallet-im-online = { git = "https://github.com/paritytech/substrate", rev = "c60f00840034017d4b7e6d20bd4fcf9a3f5b529a" }

[features]
default = []
tool = ["cargo-creator"]
permissions = ["creator-permissions"]

[workspace]
members = [
    "crates/*",
    "examples/*",
    "examples/substrate/runtime",
]
