[package]
name = "creator"
version = "0.1.2"
edition = "2018"
authors = ["enfipy <enfipy@gmail.com>", "olvyko <olvyko@gmail.com>"]
description = "Mobile Game Framework"
repository = "https://github.com/creator-rs/creator"
license = "Apache-2.0"
keywords = ["build", "android", "ios", "substrate"]
readme = "README.md"
exclude = [".github/**/*"]

[dependencies]
cargo-creator = { path = "crates/cargo-creator", version = "0.1.2", optional = true }
creator-permissions = { path = "crates/creator-permissions", version = "0.1.2", optional = true }

[features]
tool = ["cargo-creator"]
permissions = ["creator-permissions"]

[workspace]
members = [
    "crates/*",
    "examples/*",
    "examples/substrate/runtime",
]
