[package]
name = "paint"
version = "0.2.1"
authors = ["enfipy <enfipy@gmail.com>", "olvyko <olvyko@gmail.com>"]
edition = "2018"

[dependencies]
creator = { version = "0.2.1", path = "../../" }
log = "0.4"
anyhow = "1.0"
itertools = "0.9"
bevy = "0.3"

[target.'cfg(target_os = "android")'.dependencies]
ndk-glue = { version = "0.2", features = ["logger"] }
android_logger = "0.9"

[lib]
name = "paintlib"
crate-type = ["lib", "cdylib"]

[package.metadata.android]
apk_label = "Creator Paint"
fullscreen = true
res = "res"
icon = "@mipmap/ic_launcher"
target_sdk_version = 29
min_sdk_version = 16
build_targets = ["aarch64-linux-android"]
