[package]
name = "threed"
version = "0.2.1"
authors = ["enfipy <enfipy@gmail.com>", "olvyko <olvyko@gmail.com>"]
edition = "2018"

[dependencies]
creator = { version = "0.2.1", path = "../../" }
log = "0.4"
anyhow = "1.0"
bevy = { version = "0.3", features = ["bevy_gilrs", "bevy_gltf", "bevy_wgpu", "bevy_winit", "render", "png", "hdr"], default-features = false }
# bevy = { path = "../../../bevy", features = ["bevy_gilrs", "bevy_gltf", "bevy_wgpu", "bevy_winit", "render", "png", "hdr"], default-features = false }

[lib]
name = "threedlib"

[package.metadata.android]
apk_label = "Creator 3D"
fullscreen = true
assets = "assets"
res = "res"
icon = "@mipmap/ic_launcher"
target_sdk_version = 29
min_sdk_version = 16
build_targets = ["aarch64-linux-android"]
