[package]
name = "cargo-creator"
version = "0.1.1"
edition = "2018"
authors = ["enfipy <enfipy@gmail.com>", "olvyko <olvyko@gmail.com>"]
description = "Mobile Game Framework"
repository = "https://github.com/creator-rs/creator"
license = "Apache-2.0"
keywords = ["tool", "android", "ios"]
readme = "../../README.md"

[dependencies]
anyhow = "1.0"
dunce = "1.0"
env_logger = "0.7.1"
log = "0.4.8"
ndk-build = { version = "0.1.2" }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
toml = "0.5.6"
