[package]
name = "explorer"
version = "0.2.1"
authors = ["enfipy <enfipy@gmail.com>", "olvyko <olvyko@gmail.com>"]
edition = "2018"

[dependencies]
creator = { version = "0.2.1", path = "../../" }
log = "0.4"
anyhow = "1.0"
substrate-subxt = "0.13"
bevy = "0.3"
tokio = { version = "0.3.5", features = ["sync", "macros"] }

[target.'cfg(target_os = "android")'.dependencies]
ndk-glue = { version = "0.2", features = ["logger"] }
android_logger = "0.9"

[lib]
name = "explorerlib"
crate-type = ["lib", "cdylib"]

[package.metadata.android]
apk_label = "Creator Explorer"
fullscreen = true
assets = "assets"
res = "res"
icon = "@mipmap/ic_launcher"
target_sdk_version = 29
min_sdk_version = 16
build_targets = ["aarch64-linux-android"]

[[package.metadata.android.permission]]
name = "android.permission.INTERNET"
