name: CI

on:
  push:
    branches: [master]

jobs:

  app-build-ubuntu:
    name: Build App example on Ubuntu Latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Android targets
      run: |
        cd examples/app
        rustup target add armv7-linux-androideabi aarch64-linux-android i686-linux-android x86_64-linux-android
    - name: Install Cargo Creator
      run: |
        cd examples/app
        cargo install cargo-creator
    - name: Build APK
      run: |
        cd examples/app
        cargo creator build --all-features

  clean:
    name: Check code format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Run clippy for example app
        run: |
          cd examples/app
          cargo clippy --all-targets --all-features -- -D warnings -A clippy::type_complexity -A clippy::too-many-arguments
