name: CI

on:
  push:
    branches: [master]

jobs:

  app-build-ubuntu:
    name: Build App example on Ubuntu Latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Android targets
      run: |
        cd examples/app
        rustup target add armv7-linux-androideabi
        rustup target add aarch64-linux-android
        rustup target add i686-linux-android
        rustup target add x86_64-linux-android
    - name: Install Cargo Creator
      run: |
        cd examples/app
        cargo install cargo-creator
    - name: Build APK
      run: |
        cd examples/app
        cargo creator build --all-features

  clean:
    name: Check code format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt, clippy
          override: true
      - name: Check the format
        run: cargo +nightly fmt --all -- --check
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings -A clippy::type_complexity -A clippy::manual-strip
