name: CI

on:
  push:
    branches:
    - master

jobs:

  test-ubuntu:
    name: Test on Ubuntu 18.04
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose
