name: CI

on:
  push:
    branches: [master]
    paths:
    - '.github/workflows/ci.yml'
    - '**.rs'
    - '**.toml'

jobs:

  android-build-ubuntu:
    name: Build Android example on Ubuntu latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Android targets
      run: rustup target add armv7-linux-androideabi aarch64-linux-android i686-linux-android x86_64-linux-android
    - name: Install Cargo Creator
      run: cargo install --git=https://github.com/creator-rs/creator cargo-creator
    - name: Build APK
      run: |
        cd examples/3d
        creator build android --release

  apple-build-ubuntu:
    name: Build Apple example on macOS latest
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Apple targets
      run: rustup target add aarch64-apple-ios x86_64-apple-ios
    - name: Install Cargo Creator
      run: cargo install --git=https://github.com/creator-rs/creator cargo-creator
    - name: Build Apple app
      run: |
        cd examples/3d
        creator build apple --release --target=x86_64-apple-ios

  clean:
    name: Check code format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt, clippy
          override: true
      - name: Check the format
        run: cargo +nightly fmt --all -- --check
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings -A clippy::unnecessary-unwrap -A clippy::too-many-arguments
      - name: Check for deadlinks
        run: |
          cargo install cargo-deadlinks
          cargo deadlinks --check-http
