name: Docker images

on:
  push:
    branches: [master]
    paths:
    - '.github/docker/*.Dockerfile'
    - '.github/workflows/docker.yml'
    tags: ["v*"]

jobs:

  build-android-dockerfile:
    name: Build Android Dockerfile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build Android image
      run: docker build -t ghcr.io/creator-rs/android -f .github/docker/android.Dockerfile .
    - name: Publish Android docker image
      run: |
        echo ${{ secrets.DOCKER_GITHUB_TOKEN }} | docker login ghcr.io -u enfipy --password-stdin
        docker push ghcr.io/creator-rs/android
